name: 'Update ENS'
description: 'Updates ENS text record(s)'
branding:
  icon: 'award'
  color: 'green'
inputs:
  name:
    required: true
    description: 'ens name to update'
  key:
    required: true
    description: 'key to update'
  value:
    required: true
    description: 'new value'
  defenderApiKey:
    required: true
    description: 'defender relay api key'
  defenderApiSecret:
    required: true
    description: 'defender relay api secret'
  chainId:
    required: false
    description: 'chain id (1 for mainnet, 5 for goerli)'
    default: 1
outputs:
  transaction:
    description: 'transaction returned from defender relay'
runs:
  using: 'node16'
  main: 'lib/index.js'
